# PostgreSQL configuration for Learning Routes
# https://guides.rubyonrails.org/configuring.html#configuring-a-database

default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  primary:
    <<: *default
    database: learning_routes_development
  cache:
    <<: *default
    database: learning_routes_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: learning_routes_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: learning_routes_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: learning_routes_test
  cache:
    <<: *default
    database: learning_routes_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: learning_routes_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: learning_routes_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    sslmode: require
  cache:
    <<: *primary_production
    url: <%= ENV["DATABASE_CACHE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    url: <%= ENV["DATABASE_QUEUE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    url: <%= ENV["DATABASE_CABLE_URL"] %>
    migrations_paths: db/cable_migrate
